# Gradle settings
# Increase the heap size for the Gradle daemon
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8

# Enable parallel execution
org.gradle.parallel=true

# Enable build caching
org.gradle.caching=true

# Android-specific settings
android.useAndroidX=true
# Non-transitive R classes for faster builds
android.nonTransitiveRClass=true
